# Generated by Django 5.2.3 on 2026-03-20 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_energy_level', models.IntegerField()),
                ('last_assessed', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vault_Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Micro_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('energy_cost', models.IntegerField()),
                ('skip_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('vaulted', 'Vaulted'), ('flashlight', 'Flashlight'), ('completed', 'Completed'), ('intervention', 'Intervention')], default='vaulted', max_length=20)),
                ('soft_deadline', models.DateTimeField(blank=True, null=True)),
                ('parent_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.vault_goal')),
            ],
        ),
    ]
