# Generated by Django 6.0.1 on 2026-03-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='micro_task',
            name='energy_cost',
        ),
        migrations.RemoveField(
            model_name='user_state',
            name='current_energy_level',
        ),
        migrations.AddField(
            model_name='micro_task',
            name='threat',
            field=models.IntegerField(choices=[(10, 'D-Rank'), (20, 'C-Rank'), (30, 'B-Rank'), (40, 'A-Rank'), (50, 'S-Rank')], default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_state',
            name='current_stamina',
            field=models.IntegerField(choices=[(10, 'D-Rank'), (20, 'C-Rank'), (30, 'B-Rank'), (40, 'A-Rank'), (50, 'S-Rank')], default=20),
        ),
        migrations.AlterField(
            model_name='micro_task',
            name='status',
            field=models.CharField(choices=[('bounty_board', 'Bounty_Board'), ('active_hunt', 'Active_hunt'), ('tactical_retreat', 'Tactical_Retreat'), ('defeated', 'Defeated'), ('intervention', 'Intervention')], default='bounty_board', max_length=20),
        ),
    ]
