# Generated by Django 5.2.3 on 2026-05-01 14:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_conversationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationlog',
            name='message',
            field=models.TextField(default='empty'),
        ),
        migrations.AlterField(
            model_name='conversationlog',
            name='sender',
            field=models.CharField(choices=[('USER', 'User'), ('AI', 'AI')], default='USER', max_length=10),
        ),
        migrations.AlterField(
            model_name='conversationlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vault_goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micro_task', to=settings.AUTH_USER_MODEL),
        ),
    ]
