# Generated by Django 5.2.3 on 2026-05-01 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_alter_vault_goal_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='micro_task',
            name='parent_goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micro_tasks', to='planner.vault_goal'),
        ),
        migrations.AlterField(
            model_name='vault_goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
