# Generated by Django 5.2.3 on 2026-05-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_alter_micro_task_parent_goal_alter_vault_goal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='micro_task',
            name='soft_deadline',
        ),
        migrations.AddField(
            model_name='vault_goal',
            name='soft_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
